In [2]:
import numpy as np
x = np.ones((32,32,3))
print (x)

[[[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  ..., 
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  ..., 
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  ..., 
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 ..., 
 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  ..., 
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  ..., 
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]

 [[ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  ..., 
  [ 1.  1.  1.]
  [ 1.  1.  1.]
  [ 1.  1.  1.]]]


In [3]:
x.reshape((32*32*3,1))

array([[ 1.],
       [ 1.],
       [ 1.],
       ..., 
       [ 1.],
       [ 1.],
       [ 1.]])

In [5]:
a = np.random.randn(4,3)
b = np.random.randn(3,2)
c= a*b
print(c.shape)

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 

In [9]:
x = np.random.randn(1,5)
print(x)

[[-2.09850492  0.63190116  3.6877389   0.08293955  0.22365733]]


In [10]:
a = np.random.randn(12288, 150) # a.shape = (12288, 150)
b = np.random.randn(150, 45) # b.shape = (150, 45)
c = np.dot(a,b)
print(c.shape)

(12288, 45)


In [17]:
a= np.random.randn(3,4)
b= np.random.randn(4,1)
print(a)
print(b)
c = a + b.T
print (c)

[[-0.13513204  0.84589047  0.25312963  0.71163171]
 [-0.82242956 -0.25573553  0.42435208 -0.22216721]
 [ 1.7093334   1.33183493  0.67206608 -2.58705009]]
[[ 0.94055985]
 [-1.58010477]
 [ 0.429026  ]
 [-1.62165799]]
[[ 0.8054278  -0.7342143   0.68215563 -0.91002628]
 [ 0.11813028 -1.83584031  0.85337808 -1.8438252 ]
 [ 2.64989325 -0.24826985  1.10109208 -4.20870808]]


In [20]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print (c.shape)

(3, 3)


In [21]:
print(a)
print (b)
print (a[0,0]*b[0,0])

[[-0.02520076 -0.15070631 -0.20195028]
 [-0.09264302  1.13872918 -0.44580577]
 [ 0.46625541 -0.87238439 -0.58998484]]
[[-0.8109189 ]
 [-0.28144015]
 [ 1.94057099]]
0.0204357715254


In [22]:
print(c)

[[ 0.02043577  0.1222106   0.1637653 ]
 [ 0.02607347 -0.32048412  0.12546764]
 [ 0.90480173 -1.69292384 -1.14490747]]


In [40]:
import mxnet as mx
user = mx.symbol.Variable('Tweets input')

# Set dummy dimensions
k = 64
max_user = 1
max_item = 50

# user feature lookup
user = mx.symbol.Embedding(data = user, input_dim = 5, output_dim = 3, name = "GloVe \n Embeddings")

# item feature lookup
# item = mx.symbol.Embedding(data = item, input_dim = max_item, output_dim = k)

# predict by the inner product, which is elementwise product and then sum
net = user 
net = mx.symbol.Flatten(data = net, axis = 1, name = "Flatten")
net = mx.symbol.Activation(data=net, act_type = "relu" ,name="ReLU \n (32 neurons)")
net = mx.symbol.sigmoid(data=net, name = "Sigmoid")
# loss layer
# net = mx.symbol.LinearRegressionOutput(data = net, label = score)

# Visualize your network
digraph = mx.viz.plot_network(net, save_format = 'jpg')
digraph.render()
# mx.viz.plot_network(net)

'plot.gv.jpg'

In [46]:
import matplotlib.pyplot as plt

def draw_neural_net(ax, left, right, bottom, top, layer_sizes):
    '''
    Draw a neural network cartoon using matplotilb.
    
    :usage:
        >>> fig = plt.figure(figsize=(12, 12))
        >>> draw_neural_net(fig.gca(), .1, .9, .1, .9, [4, 7, 2])
    
    :parameters:
        - ax : matplotlib.axes.AxesSubplot
            The axes on which to plot the cartoon (get e.g. by plt.gca())
        - left : float
            The center of the leftmost node(s) will be placed here
        - right : float
            The center of the rightmost node(s) will be placed here
        - bottom : float
            The center of the bottommost node(s) will be placed here
        - top : float
            The center of the topmost node(s) will be placed here
        - layer_sizes : list of int
            List of layer sizes, including input and output dimensionality
    '''
    n_layers = len(layer_sizes)
    v_spacing = (top - bottom)/float(max(layer_sizes))
    h_spacing = (right - left)/float(len(layer_sizes) - 1)
    # Nodes
    for n, layer_size in enumerate(layer_sizes):
        layer_top = v_spacing*(layer_size - 1)/2. + (top + bottom)/2.
        for m in xrange(layer_size):
            circle = plt.Circle((n*h_spacing + left, layer_top - m*v_spacing), v_spacing/4.,
                                color='w', ec='k', zorder=4)
            ax.add_artist(circle)
    # Edges
    for n, (layer_size_a, layer_size_b) in enumerate(zip(layer_sizes[:-1], layer_sizes[1:])):
        layer_top_a = v_spacing*(layer_size_a - 1)/2. + (top + bottom)/2.
        layer_top_b = v_spacing*(layer_size_b - 1)/2. + (top + bottom)/2.
        for m in xrange(layer_size_a):
            for o in xrange(layer_size_b):
                line = plt.Line2D([n*h_spacing + left, (n + 1)*h_spacing + left],
                                  [layer_top_a - m*v_spacing, layer_top_b - o*v_spacing], c='k')
                ax.add_artist(line)

fig = plt.figure(figsize=(12, 12))
ax = fig.gca()
ax.axis('off')
draw_neural_net(ax, .1, .9, .1, .9, [4, 7, 2])
fig.savefig('nn.png')

NameError: name 'xrange' is not defined